spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration

dynamo:
  region: ${DYNAMO_REGION:us-east-1}
  endpoint: ${DYNAMO_ENDPOINT:}
  table:
    users: ${DYNAMO_USERS_TABLE:users}
    recipes: ${DYNAMO_RECIPES_TABLE:recipes}
    user-lists: ${DYNAMO_USER_LISTS_TABLE:user_lists}
